CREATE DATABASE aaa;
USE aaa;
CREATE TABLE blog (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  created_time VARCHAR(20) NOT NULL,
  updated_time VARCHAR(20) NOT NULL,
  title VARCHAR(500) NOT NULL,
  content VARCHAR(5000) NOT NULL
);